image: gitlab-radio-lib-runner-image-update

stages:
  - test
  - deployment

job-test:
  stage: test

  before_script:
    - ceedling new _tests
    - cp tests/project.yml _tests
    - cd _tests
    - ceedling clobber

  script:
    - ceedling gcov:all utils:gcov

  after_script:
    - REPORT_HTML_FILE="_tests/build/artifacts/gcov/GcovCoverageResults.html"
    - test -f $REPORT_HTML_FILE && echo "Global coverage:" $(echo "cat //html/body/table[1]/tr[3]/td/table/tr[2]/td[7]" | xmllint --html --shell $REPORT_HTML_FILE | grep 'td class' | cut -d'>' -f2 | cut -d'%' -f1)"%"

  coverage: '/Global coverage: ([\d\.]*.) %/'

  artifacts:
    paths:
      - _tests/build/artifacts/gcov
    when: always

job-deployment:
  stage: deployment

  script:
    - GIT_TAG=$(git describe --tags)
    - git config --global user.email "smtcbot@semtech.com"
    - git config --global user.name "smtcbot"
    - git clone https://gitlab-ci-token:${GITBOT_TOKEN}@eugit1.semtech.com/radio_drivers/llcc68/llcc68_driver.git
    - cd llcc68_driver
    - git checkout master
    - rm -rf *
    - cp ../LICENSE.txt .
    - cp ../README.md .
    - cp ../CHANGELOG.md .
    - cp -r ../src .
    - git add .
    - git commit -m "Release $GIT_TAG"
    - git push
    - git tag $GIT_TAG
    - git push origin $GIT_TAG

  only:
    - /^v(([0-9]+)\.([0-9]+)\.([0-9]+))$/

  except:
    - branches
    - triggers
    - schedules
